### ISSUE TITLE
Broken XOR function example link in README

### ISSUE THREAD

**Issue by eherbert** [ctongfei/nexus#21]

**Comment by ctongfei** [comment]
Fixed -- thanks! I mistakenly untracked some test files.
This project right now is still very preliminary stage and should not be used for any research/production purposes. I'll work on this after the release of PyTorch 1.0.

**Comment by eherbert** [comment]
It's seems like a great project! I like programming in Scala the most, but haven't been happy with the DL libraries thus far, and PyTorch is my favorite of the Python options, so this project seems promising.

**Comment by ctongfei** [comment]
Thanks for the interest! It's very encouraging that other people (esp. PhD students like me) are interested in this :-)
