### ISSUE TITLE
object THJNI is not a member of package nexus.torch.jni

### ISSUE THREAD

**Issue by eherbert** [ctongfei/nexus#22]
Got this compiling with sbt. Is the current version able to be built?

![screenshot at 2018-09-29 18-24-48](https://user-images.githubusercontent.com/17410721/46251005-6e60e000-c415-11e8-9d91-af09d58033b5.png)

**Comment by ctongfei** [comment]
The Torch core is not ready yet -- PyTorch's ABI kept changing from 0.4 -> 0.4.1 -> 1.0 so that is now broken.
You can remove `torch` from the `.sbt` file and just use the `jvm-ref-backend` (JVM reference backend, very slow, but runnable).

**Comment by ctongfei** [comment]
If you need to build the Torch SWIG bridge btw the C++ code and JVM, you need to first build ATen in PyTorch from source then use the `build.sh` in the `nexus/torch` directory. It is a lot hassle and I do not recommend doing that before PyTorch's ABI stabilized after 1.0 and I have time to sort that out.

**Comment by ctongfei** [comment]
Now fixed with PyTorch 1.0.
