### ISSUE TITLE
NEScala unconference session

### ISSUE THREAD

**Issue by ryan-williams** [ctongfei/nexus#35]
A few of us have talked about doing a session around understanding / using / contributing to nexus tomorrow at the NEScala unconference.

If @ctongfei or anyone wants to discuss or participate remotely, let me know!

cc @non

**Comment by ctongfei** [comment]
@ryan-williams Thanks! Contributions are welcome!
I'm quite busy working with my own PhD stuff so I haven't touched it for a while. I'd like to discuss remotely!
When are you doing the unconference? I'm in Baltimore right now and potentially can be in Philadelphia in an hour or so :-)

**Comment by ryan-williams** [comment]
We appreciated you calling in on short notice @ctongfei, thanks again. cc @EmergentOrder
